version: "3"

services:
  frontend:
    container_name: frontend
    image: ghcr.io/littleknitsstory/frontend:latest
    ports:
      - "63000:80/tcp"
    volumes:
      - /app/node_modules
      - .:/app