export const ROUTES = {
  HOME: "/",
  ARTICLES: "/articles",
  PRODUCTS: "/products",
  CONTACTS: "/contacts",
  CART: "/cart",
  ORDERING: "cart/ordering",
  LOGIN: "/login",
  FAVORITE_PRODUCTS: "/favorites",
  PRIVACY_POLICY: "/privacyPolicy",
  PROFILE: "/profile",
  PROFILE_INFO: "/profile/info",
  PROFILE_COURSES: "/profile/courses",
  PROFILE_ARTICLES: "/profile/articles",
  PROFILE_ORDERS: "/profile/orders",
  BOOKMARKS: "/bookmarks",
};
